### ISSUE TITLE
Misc todo (from parse.py)

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mini-kep#11]
TODO:
====
- [ ] dir structure 
- [ ] list of notebooks
- [ ] frontend.md 
- [x] code review *parse.py*
- [ ] transform GOV_EXPENSE_ACCUM, GOV_REVENUE_ACCUM, GOV_SURPLUS_ACCUM
- [ ] interface to processed data 
- [ ] generate excel wtih variable names 

Tasks
====

List of notebooks
-------------------
Make notebook README.MD:
- vintages / revisions (make markdown based on MS Word)
- datalab 
- inflation components
- bank reserves vs oil  
- variations in variables
- macro assumptions for stress testing 

OUT OF SCOPE
-----------------
-  read SEP + update KEP with SEP data  
-  prior to 1999

Datadriven comment
-----------------------
- Using incomplete dir structure  
- DAG for economist

```    
    # REQUIREMENT: 
    # pick new vars by requirement for features   
    # var desciptions by section with latest data
    # detrended data
    # revisions analysis
    # dataset organisation - what we want:
        # latest dataset
        # variable by vintages
        # seasonally adjusted series
        
        
    
    # TODO-PARSING:         
    # convert more existing parsing definitions to cfg.py    
    # add more control datapoints        
    
    #FIXME: generate Excel files and plots
    #def to_excel(dfs, filename):
    #    dfa, dfq, dfm = dfs
    #    with pd.ExcelWriter(filename) as writer:
    #        dfa.to_excel(writer, sheet_name='year')
    #        dfq.to_excel(writer, sheet_name='quarter')
    #        dfm.to_excel(writer, sheet_name='month')
    #        #FIXME - write variable names to sheet, by section 
    #
    ##for file in [config.XLSX_FILE, config.XLS_FILE]:
    ##   to_excel(file)
